-- Generated QBX vehicles table entries
    gb811s2 = {
        name = '811 S2',
        brand = 'Pfister',
        model = 'gb811s2',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gb811s2`,
    },
    gbbanshees = {
        name = 'Banshee S',
        brand = 'Bravado',
        model = 'gbbanshees',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gbbanshees`,
    },
    gbemerussb1 = {
        name = 'Emerus SB1',
        brand = 'Progen',
        model = 'gbemerussb1',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gbemerussb1`,
    },
    gbprospero = {
        name = 'Prospero',
        brand = 'Pegassi',
        model = 'gbprospero',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gbprospero`,
    },
    gbtr3s = {
        name = 'TR3-S',
        brand = 'Progen',
        model = 'gbtr3s',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gbtr3s`,
    },
    gbadmiral = {
        name = 'Admiral',
        brand = 'Dundreary',
        model = 'gbadmiral',
        price = 5000,
        category = 'sedans',
        type = 'automobile',
        hash = `gbadmiral`,
    },
    gbargento7f = {
        name = 'Argento 7F',
        brand = 'Obey',
        model = 'gbargento7f',
        price = 5000,
        category = 'sedans',
        type = 'automobile',
        hash = `gbargento7f`,
    },
    gbharmann = {
        name = 'Harmann',
        brand = 'Benefactor',
        model = 'gbharmann',
        price = 5000,
        category = 'sedans',
        type = 'automobile',
        hash = `gbharmann`,
    },
    gbimpaler = {
        name = 'Imapaler',
        brand = 'Declasse',
        model = 'gbimpaler',
        price = 5000,
        category = 'sedans',
        type = 'automobile',
        hash = `gbimpaler`,
    },
    gbstanierle = {
        name = 'Stainer LE',
        brand = 'Vapid',
        model = 'gbstanierle',
        price = 5000,
        category = 'sedans',
        type = 'automobile',
        hash = `gbstanierle`,
    },
    gbcomets2r = {
        name = 'Comet S2R',
        brand = 'Pfister',
        model = 'gbcomets2r',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbcomets2r`,
    },
    gbcomets2rc = {
        name = 'Comet S2R C',
        brand = 'Pfister',
        model = 'gbcomets2rc',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbcomets2rc`,
    },
    gbeon = {
        name = 'Eon',
        brand = 'Coil',
        model = 'gbeon',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbeon`,
    },
    gbmilano = {
        name = 'Milano',
        brand = 'Grotti',
        model = 'gbmilano',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbmilano`,
    },
    gbmogulrs = {
        name = 'Mogul RS',
        brand = 'Karin',
        model = 'gbmogulrs',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbmogulrs`,
    },
    gbneonct = {
        name = 'Neon CT',
        brand = 'Pfister',
        model = 'gbneonct',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbneonct`,
    },
    gbnexusrr = {
        name = 'Nesus RR',
        brand = 'Dinka',
        model = 'gbnexusrr',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbnexusrr`,
    },
    gbronin = {
        name = 'Ronin',
        brand = 'Emperor',
        model = 'gbronin',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbronin`,
    },
    gbschlagenr = {
        name = 'Schlagen-R',
        brand = 'Benefactor',
        model = 'gbschlagenr',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbschlagenr`,
    },
    gbschlagensp = {
        name = 'Schlagen-SP',
        brand = 'Benefactor',
        model = 'gbschlagensp',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbschlagensp`,
    },
    gbschrauber = {
        name = 'Schrauber',
        brand = 'Benefactor',
        model = 'gbschrauber',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbschrauber`,
    },
    gbschwartzers = {
        name = 'Schwartzer S',
        brand = 'Benefactor',
        model = 'gbschwartzers',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbschwartzers`,
    },
    gbsentinelgts = {
        name = 'Sentinel GTS',
        brand = 'Ubermacht',
        model = 'gbsentinelgts',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbsentinelgts`,
    },
    gbsolace = {
        name = 'Solace',
        brand = 'Dewbauchee',
        model = 'gbsolace',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbsolace`,
    },
    gbsolacev = {
        name = 'Solace Vitesse',
        brand = 'Dewbauchee',
        model = 'gbsolacev',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbsolacev`,
    },
    gbsultanrsx = {
        name = 'Sultan RSX',
        brand = 'Karin',
        model = 'gbsultanrsx',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbsultanrsx`,
    },
    gbtenfr = {
        name = 'Tenf R',
        brand = 'Obey',
        model = 'gbtenfr',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbtenfr`,
    },
    gbvivantgrb = {
        name = 'Vivant GRB',
        brand = 'Bordeaux',
        model = 'gbvivantgrb',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbvivantgrb`,
    },
    gbcometcl = {
        name = 'Comet Classic',
        brand = 'Pfister',
        model = 'gbcometcl',
        price = 5000,
        category = 'sportsclassic',
        type = 'automobile',
        hash = `gbcometcl`,
    },
    gbcomets1t = {
        name = 'Comet S1 Turbo',
        brand = 'Pfister',
        model = 'gbcomets1t',
        price = 5000,
        category = 'sportsclassic',
        type = 'automobile',
        hash = `gbcomets1t`,
    },
    gbkomodagt = {
        name = 'Komoda GT',
        brand = 'Lampadati',
        model = 'gbkomodagt',
        price = 5000,
        category = 'sportsclassic',
        type = 'automobile',
        hash = `gbkomodagt`,
    },
    gbraidillon = {
        name = 'Raidillon',
        brand = 'Toundra',
        model = 'gbraidillon',
        price = 5000,
        category = 'sportsclassic',
        type = 'automobile',
        hash = `gbraidillon`,
    },
    gbsidewinder = {
        name = 'Sidewinder',
        brand = 'Maxwell',
        model = 'gbsidewinder',
        price = 5000,
        category = 'sportsclassic',
        type = 'automobile',
        hash = `gbsidewinder`,
    },
    gbturismogt = {
        name = 'Turismo GT',
        brand = 'Grotti',
        model = 'gbturismogt',
        price = 5000,
        category = 'sportsclassic',
        type = 'automobile',
        hash = `gbturismogt`,
    },
    gbturismogts = {
        name = 'Turismo GTS',
        brand = 'Grotti',
        model = 'gbturismogts',
        price = 5000,
        category = 'sportsclassic',
        type = 'automobile',
        hash = `gbturismogts`,
    },
    gbdominatorgsx = {
        name = 'Dominator GSX',
        brand = 'Vapid',
        model = 'gbdominatorgsx',
        price = 5000,
        category = 'muscle',
        type = 'automobile',
        hash = `gbdominatorgsx`,
    },
    gbhades = {
        name = 'Hades',
        brand = 'Dundreary',
        model = 'gbhades',
        price = 5000,
        category = 'muscle',
        type = 'automobile',
        hash = `gbhades`,
    },
    gbtahomagt = {
        name = 'Tahoma GT',
        brand = 'Declasse',
        model = 'gbtahomagt',
        price = 5000,
        category = 'muscle',
        type = 'automobile',
        hash = `gbtahomagt`,
    },
    gbbriosof = {
        name = 'Brioso Fulmine',
        brand = 'Grotti',
        model = 'gbbriosof',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        hash = `gbbriosof`,
    },
    gbclubxr = {
        name = 'Club XR',
        brand = 'BF',
        model = 'gbclubxr',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        hash = `gbclubxr`,
    },
    gbirisz = {
        name = 'Iris Z',
        brand = 'Bollokan',
        model = 'gbirisz',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        hash = `gbirisz`,
    },
    gbissimetro = {
        name = 'Issi Metro',
        brand = 'Weeny',
        model = 'gbissimetro',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        hash = `gbissimetro`,
    },
    gbvivant = {
        name = 'Vivant',
        brand = 'Bordeaux',
        model = 'gbvivant',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        hash = `gbvivant`,
    },
    gbgresleystx = {
        name = 'Gresley STX',
        brand = 'Bravado',
        model = 'gbgresleystx',
        price = 5000,
        category = 'suv',
        type = 'automobile',
        hash = `gbgresleystx`,
    },
    gbstarlight = {
        name = 'Starlight',
        brand = 'Vulcar',
        model = 'gbstarlight',
        price = 5000,
        category = 'suv',
        type = 'automobile',
        hash = `gbstarlight`,
    },
    gbsapphire = {
        name = 'Sapphire',
        brand = 'Enus',
        model = 'gbsapphire',
        price = 5000,
        category = 'coupes',
        type = 'automobile',
        hash = `gbsapphire`,
    },
    gbbisonstx = {
        name = 'Bison STX',
        brand = 'Bravado',
        model = 'gbbisonstx',
        price = 5000,
        category = 'vans',
        type = 'automobile',
        hash = `gbbisonstx`,
    },
    gbboxboy = {
        name = 'Boxboy',
        brand = 'Brute',
        model = 'gbboxboy',
        price = 5000,
        category = 'vans',
        type = 'automobile',
        hash = `gbboxboy`,
    },
    gbboxboyft = {
        name = 'Boxboy Food Truck',
        brand = 'Brute',
        model = 'gbboxboyft',
        price = 5000,
        category = 'vans',
        type = 'automobile',
        hash = `gbboxboyft`,
    },
    gbesperta = {
        name = 'Esperta',
        brand = 'Bravado',
        model = 'gbesperta',
        price = 5000,
        category = 'vans',
        type = 'automobile',
        hash = `gbesperta`,
    },
    gbbisonhf = {
        name = 'Bison HF',
        brand = 'Bravado',
        model = 'gbbisonhf',
        price = 5000,
        category = 'offroad',
        type = 'automobile',
        hash = `gbbisonhf`,
    },
    gblod4 = {
        name = 'LOD 4',
        brand = 'Coil',
        model = 'gblod4',
        price = 5000,
        category = 'offroad',
        type = 'automobile',
        hash = `gblod4`,
    },
    gbmojave = {
        name = 'Mojave',
        brand = 'Karin',
        model = 'gbmojave',
        price = 5000,
        category = 'offroad',
        type = 'automobile',
        hash = `gbmojave`,
    },
    gbterrorizer = {
        name = 'Terrorizer',
        brand = 'HVY',
        model = 'gbterrorizer',
        price = 5000,
        category = 'offroad',
        type = 'automobile',
        hash = `gbterrorizer`,
    },
    gbtaxiargento7f = {
        name = 'Argento 7F Taxi',
        brand = 'Obey',
        model = 'gbtaxiargento7f',
        price = 5000,
        category = 'service',
        type = 'automobile',
        hash = `gbtaxiargento7f`,
    },
    gbtaxieon = {
        name = 'Eon Taxi',
        brand = 'Coil',
        model = 'gbtaxieon',
        price = 5000,
        category = 'service',
        type = 'automobile',
        hash = `gbtaxieon`,
    },
    gbtaxistanierle = {
        name = 'Stainer LE Taxi',
        brand = 'Vapid',
        model = 'gbtaxistanierle',
        price = 5000,
        category = 'service',
        type = 'automobile',
        hash = `gbtaxistanierle`,
    },
    gbtaxistarlight = {
        name = 'Starlight Taxi',
        brand = 'Vulcar',
        model = 'gbtaxistarlight',
        price = 5000,
        category = 'service',
        type = 'automobile',
        hash = `gbtaxistarlight`,
    },
    gbvoyagerg = {
        name = 'Voyager Trash Truck',
        brand = 'MTL',
        model = 'gbvoyagerg',
        price = 5000,
        category = 'service',
        type = 'automobile',
        hash = `gbvoyagerg`,
    },
    gbvoyager = {
        name = 'Voyager 6x4-T',
        brand = 'MTL',
        model = 'gbvoyager',
        price = 5000,
        category = 'commercial',
        type = 'automobile',
        hash = `gbvoyager`,
    },
    gbvoyager2 = {
        name = 'Voyager 4x2-T',
        brand = 'MTL',
        model = 'gbvoyager2',
        price = 5000,
        category = 'commercial',
        type = 'automobile',
        hash = `gbvoyager2`,
    },
    gbvoyagerb = {
        name = 'Voyager 6x4-B',
        brand = 'MTL',
        model = 'gbvoyagerb',
        price = 5000,
        category = 'commercial',
        type = 'automobile',
        hash = `gbvoyagerb`,
    },
    gbvoyagerb2 = {
        name = 'Voyager 4x2-B',
        brand = 'MTL',
        model = 'gbvoyagerb2',
        price = 5000,
        category = 'commercial',
        type = 'automobile',
        hash = `gbvoyagerb2`,
    },
    gbvoyagerh = {
        name = 'Voyager 6x2-H',
        brand = 'MTL',
        model = 'gbvoyagerh',
        price = 5000,
        category = 'commercial',
        type = 'automobile',
        hash = `gbvoyagerh`,
    },
    gbemsbisonstx = {
        name = 'Bison STX Ambulance',
        brand = 'Bravado',
        model = 'gbemsbisonstx',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbemsbisonstx`,
    },
    gbemsesperta = {
        name = 'Esperta Ambulance',
        brand = 'Bravado',
        model = 'gbemsesperta',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbemsesperta`,
    },
    gbfirevoyager = {
        name = 'Voyager Fire Truck',
        brand = 'MTL',
        model = 'gbfirevoyager',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbfirevoyager`,
    },
    gbpolbisonhf = {
        name = 'Bison HF Police',
        brand = 'Bravado',
        model = 'gbpolbisonhf',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolbisonhf`,
    },
    gbpolbisonstx = {
        name = 'Bison STX Police',
        brand = 'Bravado',
        model = 'gbpolbisonstx',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolbisonstx`,
    },
    gbpolcometcl = {
        name = 'Comet Classic Police',
        brand = 'Pfister',
        model = 'gbpolcometcl',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolcometcl`,
    },
    gbpolcomets2r = {
        name = 'Comet S2R Police',
        brand = 'Pfister',
        model = 'gbpolcomets2r',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolcomets2r`,
    },
    gbpoldomgsx = {
        name = 'Dominator GSX Police',
        brand = 'Vapid',
        model = 'gbpoldomgsx',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpoldomgsx`,
    },
    gbpolprospero = {
        name = 'Prospero Police',
        brand = 'Pegassi',
        model = 'gbpolprospero',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolprospero`,
    },
    gbpolsolace = {
        name = 'Solace Police',
        brand = 'Dewbauchee',
        model = 'gbpolsolace',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolsolace`,
    },
    gbpolstanier = {
        name = 'Stainer LE Police',
        brand = 'Vapid',
        model = 'gbpolstanier',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolstanier`,
    },
    gbpolstarlight = {
        name = 'Starlight Police',
        brand = 'Vulcar',
        model = 'gbpolstarlight',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolstarlight`,
    },
    gbpolsultanrsx = {
        name = 'Sultan RSX Police',
        brand = 'Karin',
        model = 'gbpolsultanrsx',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolsultanrsx`,
    },
    gbpoltahomagt = {
        name = 'Tahoma GT Police',
        brand = 'Declasse',
        model = 'gbpoltahomagt',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpoltahomagt`,
    },
    gbpoltr3s = {
        name = 'TR3-S Police',
        brand = 'Progen',
        model = 'gbpoltr3s',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpoltr3s`,
    },
    gbpolturismogt = {
        name = 'Turismo GT Police',
        brand = 'Grotti',
        model = 'gbpolturismogt',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolturismogt`,
    },
    gbarcherpro2 = {
        name = 'Archer Pro II',
        brand = 'Maibatsu',
        model = 'gbarcherpro2',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbarcherpro2`,
    },
    gbargento2f = {
        name = 'Argento 2F',
        brand = 'Obey',
        model = 'gbargento2f',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbargento2f`,
    },
    gbargento7fs = {
        name = 'Argento 7F Sportsback',
        brand = 'Obey',
        model = 'gbargento7fs',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbargento7fs`,
    },
    gbcheetahs = {
        name = 'Grotti Cheetah S',
        brand = 'Grotti',
        model = 'gbcheetahs',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gbcheetahs`,
    },
    gbcometclf = {
        name = 'Comet Classic Florio',
        brand = 'Pfister',
        model = 'gbcometclf',
        price = 5000,
        category = 'sportsclassic',
        type = 'automobile',
        hash = `gbcometclf`,
    },
    gbcomets1tf = {
        name = 'Comet S1 Turbo Florio',
        brand = 'Pfister',
        model = 'gbcomets1tf',
        price = 5000,
        category = 'sportsclassic',
        type = 'automobile',
        hash = `gbcomets1tf`,
    },
    gbcyphergts = {
        name = 'Cypher GTS',
        brand = 'Ubermacht',
        model = 'gbcyphergts',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbcyphergts`,
    },
    gbdelivere = {
        name = 'Deliver-E',
        brand = 'Hijak',
        model = 'gbdelivere',
        price = 5000,
        category = 'commercial',
        type = 'automobile',
        hash = `gbdelivere`,
    },
    gbechelon = {
        name = 'Echelon',
        brand = 'BF',
        model = 'gbechelon',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbechelon`,
    },
    gbechelons = {
        name = 'Echelon Sportsback',
        brand = 'BF',
        model = 'gbechelons',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbechelons`,
    },
    gbelegyrh2 = {
        name = 'Elegy RH2',
        brand = 'Annis',
        model = 'gbelegyrh2',
        price = 5000,
        category = 'sportsclassic',
        type = 'automobile',
        hash = `gbelegyrh2`,
    },
    gbemssteed = {
        name = 'Steed Ambulance',
        brand = 'Vapid',
        model = 'gbemssteed',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbemssteed`,
    },
    gberotiq = {
        name = 'E-Rotiq',
        brand = 'Bollokan',
        model = 'gberotiq',
        price = 5000,
        category = 'suv',
        type = 'automobile',
        hash = `gberotiq`,
    },
    gbesurfer = {
        name = 'e-Surfer',
        brand = 'BF',
        model = 'gbesurfer',
        price = 5000,
        category = 'vans',
        type = 'automobile',
        hash = `gbesurfer`,
    },
    gbhedra = {
        name = 'Hedra',
        brand = 'Vulcar',
        model = 'gbhedra',
        price = 5000,
        category = 'sedans',
        type = 'automobile',
        hash = `gbhedra`,
    },
    gbhedrakombi = {
        name = 'Hedra Kombi',
        brand = 'Vulcar',
        model = 'gbhedrakombi',
        price = 5000,
        category = 'sedans',
        type = 'automobile',
        hash = `gbhedrakombi`,
    },
    gbhurricane = {
        name = 'Hurricane',
        brand = 'Brute',
        model = 'gbhurricane',
        price = 5000,
        category = 'muscle',
        type = 'automobile',
        hash = `gbhurricane`,
    },
    gbimpalerdlx = {
        name = 'Impaler Deluxe',
        brand = 'Declasse',
        model = 'gbimpalerdlx',
        price = 5000,
        category = 'muscle',
        type = 'automobile',
        hash = `gbimpalerdlx`,
    },
    gbmochi = {
        name = 'Mochi',
        brand = 'Annis',
        model = 'gbmochi',
        price = 5000,
        category = 'compacts',
        type = 'automobile',
        hash = `gbmochi`,
    },
    gbmugello = {
        name = 'Mugello',
        brand = 'Grotti',
        model = 'gbmugello',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gbmugello`,
    },
    gbpoladmiral = {
        name = 'Admiral Police',
        brand = 'Vapid',
        model = 'gbpoladmiral',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpoladmiral`,
    },
    gbpolargento7f = {
        name = 'Argento 7F Police',
        brand = 'Obey',
        model = 'gbpolargento7f',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolargento7f`,
    },
    gbpolbanshees = {
        name = 'Banshee S Police',
        brand = 'Bravado',
        model = 'gbpolbanshees',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolbanshees`,
    },
    gbpolclubxr = {
        name = 'Club XR Police',
        brand = 'BF',
        model = 'gbpolclubxr',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolclubxr`,
    },
    gbpolechelon = {
        name = 'Echelon Police',
        brand = 'BF',
        model = 'gbpolechelon',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolechelon`,
    },
    gbpoleon = {
        name = 'Eon Police',
        brand = 'Coil',
        model = 'gbpoleon',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpoleon`,
    },
    gbpolesperta = {
        name = 'Esperta Police',
        brand = 'Bravado',
        model = 'gbpolesperta',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolesperta`,
    },
    gbpolgresley = {
        name = 'Gresley Police',
        brand = 'Bravado',
        model = 'gbpolgresley',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolgresley`,
    },
    gbpolhedra = {
        name = 'Hedra Police',
        brand = 'Vulcar',
        model = 'gbpolhedra',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolhedra`,
    },
    gbpolimpaler = {
        name = 'Impaler Police',
        brand = 'Declasse',
        model = 'gbpolimpaler',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolimpaler`,
    },
    gbpolmojave = {
        name = 'Mojave Police',
        brand = 'Karin',
        model = 'gbpolmojave',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolmojave`,
    },
    gbpolscoutgsx = {
        name = 'Scout GSX Police',
        brand = 'Vapid',
        model = 'gbpolscoutgsx',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolscoutgsx`,
    },
    gbpolsentinelgts = {
        name = 'Sentinel GTS Police',
        brand = 'Ubermacht',
        model = 'gbpolsentinelgts',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolsentinelgts`,
    },
    gbpolstanier = {
        name = 'Stainer LE Police',
        brand = 'Vapid',
        model = 'gbpolstanier',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolstanier`,
    },
    gbpolsteedvan = {
        name = 'Steed Police',
        brand = 'Vapid',
        model = 'gbpolsteedvan',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolsteedvan`,
    },
    gbpolterrorizer = {
        name = 'Terrorizer Police',
        brand = 'HVY',
        model = 'gbpolterrorizer',
        price = 5000,
        category = 'emergency',
        type = 'automobile',
        hash = `gbpolterrorizer`,
    },
    gbretinueloz = {
        name = 'Retinue Lozspeed',
        brand = 'Vapid',
        model = 'gbretinueloz',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbretinueloz`,
    },
    gbromulus = {
        name = 'Romulus',
        brand = 'Annis',
        model = 'gbromulus',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbromulus`,
    },
    gbrumina = {
        name = 'Rumina',
        brand = 'Annis',
        model = 'gbrumina',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbrumina`,
    },
    gbscoutgsx = {
        name = 'Scout GSX',
        brand = 'Vapid',
        model = 'gbscoutgsx',
        price = 5000,
        category = 'suv',
        type = 'automobile',
        hash = `gbscoutgsx`,
    },
    gbsteedcrew = {
        name = 'Steed Crewmate',
        brand = 'Vapid',
        model = 'gbsteedcrew',
        price = 5000,
        category = 'vans',
        type = 'automobile',
        hash = `gbsteedcrew`,
    },
    gbsteedvan = {
        name = 'Steed',
        brand = 'Vapid',
        model = 'gbsteedvan',
        price = 5000,
        category = 'vans',
        type = 'automobile',
        hash = `gbsteedvan`,
    },
    gbtempestafs = {
        name = 'Tempesta Fuoristrada',
        brand = 'Pegassi',
        model = 'gbtempestafs',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gbtempestafs`,
    },
    gbvigerorat = {
        name = 'Vigero Rattler',
        brand = 'Declasse',
        model = 'gbvigerorat',
        price = 5000,
        category = 'muscle',
        type = 'automobile',
        hash = `gbvigerorat`,
    },
    gbzeitgeist = {
        name = 'Zeitgeist',
        brand = 'Benefactor-Progen',
        model = 'gbzeitgeist',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gbzeitgeist`,
    },
    gbzr350 = {
        name = 'ZR350',
        brand = 'Annis',
        model = 'gbzr350',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbzr350`,
    },
    gbbuffalohf = {
        name = 'Buffalo HF',
        brand = 'Bravado',
        model = 'gbbuffalohf',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbbuffalohf`,
    },
    gbnexus1 = {
        name = 'Nexus',
        brand = 'Dinka',
        model = 'gbnexus1',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbnexus1`,
    },
    gbtokage = {
        name = 'Tokage JDM',
        brand = 'Dinka',
        model = 'gbtokage',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbtokage`,
    },
    gbtokage2 = {
        name = 'Tokage USDM',
        brand = 'Dinka',
        model = 'gbtokage2',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbtokage2`,
    },
    gbnobile = {
        name = 'Nobile',
        brand = 'Grotti',
        model = 'gbnobile',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gbnobile`,
    },
    gbzero = {
        name = 'Zero',
        brand = 'Grotti',
        model = 'gbzero',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gbzero`,
    },
    gbdice = {
        name = 'Dice',
        brand = 'Karin',
        model = 'gbdice',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbdice`,
    },
    gbkisairs = {
        name = 'Kisai RS',
        brand = 'Karin',
        model = 'gbkisairs',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbkisairs`,
    },
    gbshogun = {
        name = 'Shogun',
        brand = 'Karin',
        model = 'gbshogun',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbshogun`,
    },
    gblaner4fh = {
        name = 'Laner 4FH',
        brand = 'Obey',
        model = 'gblaner4fh',
        price = 5000,
        category = 'sedans',
        type = 'automobile',
        hash = `gblaner4fh`,
    },
    gbtoreroxpr1 = {
        name = 'Torero XPR-1',
        brand = 'Pegassi',
        model = 'gbtoreroxpr1',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gbtoreroxpr1`,
    },
    gbmeteor = {
        name = 'Meteor',
        brand = 'Pfister',
        model = 'gbmeteor',
        price = 5000,
        category = 'sports',
        type = 'automobile',
        hash = `gbmeteor`,
    },
    gbemerus = {
        name = 'Emerus',
        brand = 'Progen',
        model = 'gbemerus',
        price = 5000,
        category = 'super',
        type = 'automobile',
        hash = `gbemerus`,
    },
    gbcaracaragsx = {
        name = 'Caracara GSX',
        brand = 'Vapid',
        model = 'gbcaracaragsx',
        price = 5000,
        category = 'offroad',
        type = 'automobile',
        hash = `gbcaracaragsx`,
    },
    gbdomle = {
        name = 'Dominator LE',
        brand = 'Vapid',
        model = 'gbdomle',
        price = 5000,
        category = 'muscle',
        type = 'automobile',
        hash = `gbdomle`,
    },
