QBCore.Shared.Vehicles = {
    ['gb811s2'] = {
        ['name'] = '811 S2',
        ['brand'] = 'Pfister',
        ['model'] = 'gb811s2',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gb811s2`,
        ['shop'] = 'pdm',
    },
    ['gbbanshees'] = {
        ['name'] = 'Banshee S',
        ['brand'] = 'Bravado',
        ['model'] = 'gbbanshees',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbbanshees`,
        ['shop'] = 'pdm',
    },
    ['gbemerussb1'] = {
        ['name'] = 'Emerus SB1',
        ['brand'] = 'Progen',
        ['model'] = 'gbemerussb1',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbemerussb1`,
        ['shop'] = 'pdm',
    },
    ['gbprospero'] = {
        ['name'] = 'Prospero',
        ['brand'] = 'Pegassi',
        ['model'] = 'gbprospero',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbprospero`,
        ['shop'] = 'pdm',
    },
    ['gbtr3s'] = {
        ['name'] = 'TR3-S',
        ['brand'] = 'Progen',
        ['model'] = 'gbtr3s',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbtr3s`,
        ['shop'] = 'pdm',
    },
    ['gbadmiral'] = {
        ['name'] = 'Admiral',
        ['brand'] = 'Dundreary',
        ['model'] = 'gbadmiral',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbadmiral`,
        ['shop'] = 'pdm',
    },
    ['gbargento7f'] = {
        ['name'] = 'Argento 7F',
        ['brand'] = 'Obey',
        ['model'] = 'gbargento7f',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbargento7f`,
        ['shop'] = 'pdm',
    },
    ['gbharmann'] = {
        ['name'] = 'Harmann',
        ['brand'] = 'Benefactor',
        ['model'] = 'gbharmann',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbharmann`,
        ['shop'] = 'pdm',
    },
    ['gbimpaler'] = {
        ['name'] = 'Imapaler',
        ['brand'] = 'Declasse',
        ['model'] = 'gbimpaler',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbimpaler`,
        ['shop'] = 'pdm',
    },
    ['gbstanierle'] = {
        ['name'] = 'Stainer LE',
        ['brand'] = 'Vapid',
        ['model'] = 'gbstanierle',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbstanierle`,
        ['shop'] = 'pdm',
    },
    ['gbcomets2r'] = {
        ['name'] = 'Comet S2R',
        ['brand'] = 'Pfister',
        ['model'] = 'gbcomets2r',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbcomets2r`,
        ['shop'] = 'pdm',
    },
    ['gbcomets2rc'] = {
        ['name'] = 'Comet S2R C',
        ['brand'] = 'Pfister',
        ['model'] = 'gbcomets2rc',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbcomets2rc`,
        ['shop'] = 'pdm',
    },
    ['gbeon'] = {
        ['name'] = 'Eon',
        ['brand'] = 'Coil',
        ['model'] = 'gbeon',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbeon`,
        ['shop'] = 'pdm',
    },
    ['gbmilano'] = {
        ['name'] = 'Milano',
        ['brand'] = 'Grotti',
        ['model'] = 'gbmilano',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbmilano`,
        ['shop'] = 'pdm',
    },
    ['gbmogulrs'] = {
        ['name'] = 'Mogul RS',
        ['brand'] = 'Karin',
        ['model'] = 'gbmogulrs',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbmogulrs`,
        ['shop'] = 'pdm',
    },
    ['gbneonct'] = {
        ['name'] = 'Neon CT',
        ['brand'] = 'Pfister',
        ['model'] = 'gbneonct',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbneonct`,
        ['shop'] = 'pdm',
    },
    ['gbnexusrr'] = {
        ['name'] = 'Nesus RR',
        ['brand'] = 'Dinka',
        ['model'] = 'gbnexusrr',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbnexusrr`,
        ['shop'] = 'pdm',
    },
    ['gbronin'] = {
        ['name'] = 'Ronin',
        ['brand'] = 'Emperor',
        ['model'] = 'gbronin',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbronin`,
        ['shop'] = 'pdm',
    },
    ['gbschlagenr'] = {
        ['name'] = 'Schlagen-R',
        ['brand'] = 'Benefactor',
        ['model'] = 'gbschlagenr',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbschlagenr`,
        ['shop'] = 'pdm',
    },
    ['gbschlagensp'] = {
        ['name'] = 'Schlagen-SP',
        ['brand'] = 'Benefactor',
        ['model'] = 'gbschlagensp',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbschlagensp`,
        ['shop'] = 'pdm',
    },
    ['gbschrauber'] = {
        ['name'] = 'Schrauber',
        ['brand'] = 'Benefactor',
        ['model'] = 'gbschrauber',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbschrauber`,
        ['shop'] = 'pdm',
    },
    ['gbschwartzers'] = {
        ['name'] = 'Schwartzer S',
        ['brand'] = 'Benefactor',
        ['model'] = 'gbschwartzers',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbschwartzers`,
        ['shop'] = 'pdm',
    },
    ['gbsentinelgts'] = {
        ['name'] = 'Sentinel GTS',
        ['brand'] = 'Ubermacht',
        ['model'] = 'gbsentinelgts',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbsentinelgts`,
        ['shop'] = 'pdm',
    },
    ['gbsolace'] = {
        ['name'] = 'Solace',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'gbsolace',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbsolace`,
        ['shop'] = 'pdm',
    },
    ['gbsolacev'] = {
        ['name'] = 'Solace Vitesse',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'gbsolacev',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbsolacev`,
        ['shop'] = 'pdm',
    },
    ['gbsultanrsx'] = {
        ['name'] = 'Sultan RSX',
        ['brand'] = 'Karin',
        ['model'] = 'gbsultanrsx',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbsultanrsx`,
        ['shop'] = 'pdm',
    },
    ['gbtenfr'] = {
        ['name'] = 'Tenf R',
        ['brand'] = 'Obey',
        ['model'] = 'gbtenfr',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbtenfr`,
        ['shop'] = 'pdm',
    },
    ['gbvivantgrb'] = {
        ['name'] = 'Vivant GRB',
        ['brand'] = 'Bordeaux',
        ['model'] = 'gbvivantgrb',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbvivantgrb`,
        ['shop'] = 'pdm',
    },
    ['gbcometcl'] = {
        ['name'] = 'Comet Classic',
        ['brand'] = 'Pfister',
        ['model'] = 'gbcometcl',
        ['price'] = 5000,
        ['category'] = 'sportsclassic',
        ['categoryLabel'] = 'Sports Classic',
        ['hash'] = `gbcometcl`,
        ['shop'] = 'pdm',
    },
    ['gbcomets1t'] = {
        ['name'] = 'Comet S1 Turbo',
        ['brand'] = 'Pfister',
        ['model'] = 'gbcomets1t',
        ['price'] = 5000,
        ['category'] = 'sportsclassic',
        ['categoryLabel'] = 'Sports Classic',
        ['hash'] = `gbcomets1t`,
        ['shop'] = 'pdm',
    },
    ['gbkomodagt'] = {
        ['name'] = 'Komoda GT',
        ['brand'] = 'Lampadati',
        ['model'] = 'gbkomodagt',
        ['price'] = 5000,
        ['category'] = 'sportsclassic',
        ['categoryLabel'] = 'Sports Classic',
        ['hash'] = `gbkomodagt`,
        ['shop'] = 'pdm',
    },
    ['gbraidillon'] = {
        ['name'] = 'Raidillon',
        ['brand'] = 'Toundra',
        ['model'] = 'gbraidillon',
        ['price'] = 5000,
        ['category'] = 'sportsclassic',
        ['categoryLabel'] = 'Sports Classic',
        ['hash'] = `gbraidillon`,
        ['shop'] = 'pdm',
    },
    ['gbsidewinder'] = {
        ['name'] = 'Sidewinder',
        ['brand'] = 'Maxwell',
        ['model'] = 'gbsidewinder',
        ['price'] = 5000,
        ['category'] = 'sportsclassic',
        ['categoryLabel'] = 'Sports Classic',
        ['hash'] = `gbsidewinder`,
        ['shop'] = 'pdm',
    },
    ['gbturismogt'] = {
        ['name'] = 'Turismo GT',
        ['brand'] = 'Grotti',
        ['model'] = 'gbturismogt',
        ['price'] = 5000,
        ['category'] = 'sportsclassic',
        ['categoryLabel'] = 'Sports Classic',
        ['hash'] = `gbturismogt`,
        ['shop'] = 'pdm',
    },
    ['gbturismogts'] = {
        ['name'] = 'Turismo GTS',
        ['brand'] = 'Grotti',
        ['model'] = 'gbturismogts',
        ['price'] = 5000,
        ['category'] = 'sportsclassic',
        ['categoryLabel'] = 'Sports Classic',
        ['hash'] = `gbturismogts`,
        ['shop'] = 'pdm',
    },
    ['gbdominatorgsx'] = {
        ['name'] = 'Dominator GSX',
        ['brand'] = 'Vapid',
        ['model'] = 'gbdominatorgsx',
        ['price'] = 5000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `gbdominatorgsx`,
        ['shop'] = 'pdm',
    },
    ['gbhades'] = {
        ['name'] = 'Hades',
        ['brand'] = 'Dundreary',
        ['model'] = 'gbhades',
        ['price'] = 5000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `gbhades`,
        ['shop'] = 'pdm',
    },
    ['gbtahomagt'] = {
        ['name'] = 'Tahoma GT',
        ['brand'] = 'Declasse',
        ['model'] = 'gbtahomagt',
        ['price'] = 5000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `gbtahomagt`,
        ['shop'] = 'pdm',
    },
    ['gbbriosof'] = {
        ['name'] = 'Brioso Fulmine',
        ['brand'] = 'Grotti',
        ['model'] = 'gbbriosof',
        ['price'] = 5000,
        ['category'] = 'compacts',
        ['categoryLabel'] = 'Compacts',
        ['hash'] = `gbbriosof`,
        ['shop'] = 'pdm',
    },
    ['gbclubxr'] = {
        ['name'] = 'Club XR',
        ['brand'] = 'BF',
        ['model'] = 'gbclubxr',
        ['price'] = 5000,
        ['category'] = 'compacts',
        ['categoryLabel'] = 'Compacts',
        ['hash'] = `gbclubxr`,
        ['shop'] = 'pdm',
    },
    ['gbirisz'] = {
        ['name'] = 'Iris Z',
        ['brand'] = 'Bollokan',
        ['model'] = 'gbirisz',
        ['price'] = 5000,
        ['category'] = 'compacts',
        ['categoryLabel'] = 'Compacts',
        ['hash'] = `gbirisz`,
        ['shop'] = 'pdm',
    },
    ['gbissimetro'] = {
        ['name'] = 'Issi Metro',
        ['brand'] = 'Weeny',
        ['model'] = 'gbissimetro',
        ['price'] = 5000,
        ['category'] = 'compacts',
        ['categoryLabel'] = 'Compacts',
        ['hash'] = `gbissimetro`,
        ['shop'] = 'pdm',
    },
    ['gbvivant'] = {
        ['name'] = 'Vivant',
        ['brand'] = 'Bordeaux',
        ['model'] = 'gbvivant',
        ['price'] = 5000,
        ['category'] = 'compacts',
        ['categoryLabel'] = 'Compacts',
        ['hash'] = `gbvivant`,
        ['shop'] = 'pdm',
    },
    ['gbgresleystx'] = {
        ['name'] = 'Gresley STX',
        ['brand'] = 'Bravado',
        ['model'] = 'gbgresleystx',
        ['price'] = 5000,
        ['category'] = 'suv',
        ['categoryLabel'] = 'SUV',
        ['hash'] = `gbgresleystx`,
        ['shop'] = 'pdm',
    },
    ['gbstarlight'] = {
        ['name'] = 'Starlight',
        ['brand'] = 'Vulcar',
        ['model'] = 'gbstarlight',
        ['price'] = 5000,
        ['category'] = 'suv',
        ['categoryLabel'] = 'SUV',
        ['hash'] = `gbstarlight`,
        ['shop'] = 'pdm',
    },
    ['gbsapphire'] = {
        ['name'] = 'Sapphire',
        ['brand'] = 'Enus',
        ['model'] = 'gbsapphire',
        ['price'] = 5000,
        ['category'] = 'coupes',
        ['categoryLabel'] = 'Coupes',
        ['hash'] = `gbsapphire`,
        ['shop'] = 'pdm',
    },
    ['gbbisonstx'] = {
        ['name'] = 'Bison STX',
        ['brand'] = 'Bravado',
        ['model'] = 'gbbisonstx',
        ['price'] = 5000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `gbbisonstx`,
        ['shop'] = 'pdm',
    },
    ['gbboxboy'] = {
        ['name'] = 'Boxboy',
        ['brand'] = 'Brute',
        ['model'] = 'gbboxboy',
        ['price'] = 5000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `gbboxboy`,
        ['shop'] = 'pdm',
    },
    ['gbboxboyft'] = {
        ['name'] = 'Boxboy Food Truck',
        ['brand'] = 'Brute',
        ['model'] = 'gbboxboyft',
        ['price'] = 5000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `gbboxboyft`,
        ['shop'] = 'pdm',
    },
    ['gbesperta'] = {
        ['name'] = 'Esperta',
        ['brand'] = 'Bravado',
        ['model'] = 'gbesperta',
        ['price'] = 5000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `gbesperta`,
        ['shop'] = 'pdm',
    },
    ['gbbisonhf'] = {
        ['name'] = 'Bison HF',
        ['brand'] = 'Bravado',
        ['model'] = 'gbbisonhf',
        ['price'] = 5000,
        ['category'] = 'offroad',
        ['categoryLabel'] = 'Offroad',
        ['hash'] = `gbbisonhf`,
        ['shop'] = 'pdm',
    },
    ['gblod4'] = {
        ['name'] = 'LOD 4',
        ['brand'] = 'Coil',
        ['model'] = 'gblod4',
        ['price'] = 5000,
        ['category'] = 'offroad',
        ['categoryLabel'] = 'Offroad',
        ['hash'] = `gblod4`,
        ['shop'] = 'pdm',
    },
    ['gbmojave'] = {
        ['name'] = 'Mojave',
        ['brand'] = 'Karin',
        ['model'] = 'gbmojave',
        ['price'] = 5000,
        ['category'] = 'offroad',
        ['categoryLabel'] = 'Offroad',
        ['hash'] = `gbmojave`,
        ['shop'] = 'pdm',
    },
    ['gbterrorizer'] = {
        ['name'] = 'Terrorizer',
        ['brand'] = 'HVY',
        ['model'] = 'gbterrorizer',
        ['price'] = 5000,
        ['category'] = 'offroad',
        ['categoryLabel'] = 'Offroad',
        ['hash'] = `gbterrorizer`,
        ['shop'] = 'pdm',
    },
    ['gbtaxiargento7f'] = {
        ['name'] = 'Argento 7F Taxi',
        ['brand'] = 'Obey',
        ['model'] = 'gbtaxiargento7f',
        ['price'] = 5000,
        ['category'] = 'service',
        ['categoryLabel'] = 'Service',
        ['hash'] = `gbtaxiargento7f`,
        ['shop'] = 'pdm',
    },
    ['gbtaxieon'] = {
        ['name'] = 'Eon Taxi',
        ['brand'] = 'Coil',
        ['model'] = 'gbtaxieon',
        ['price'] = 5000,
        ['category'] = 'service',
        ['categoryLabel'] = 'Service',
        ['hash'] = `gbtaxieon`,
        ['shop'] = 'pdm',
    },
    ['gbtaxistanierle'] = {
        ['name'] = 'Stainer LE Taxi',
        ['brand'] = 'Vapid',
        ['model'] = 'gbtaxistanierle',
        ['price'] = 5000,
        ['category'] = 'service',
        ['categoryLabel'] = 'Service',
        ['hash'] = `gbtaxistanierle`,
        ['shop'] = 'pdm',
    },
    ['gbtaxistarlight'] = {
        ['name'] = 'Starlight Taxi',
        ['brand'] = 'Vulcar',
        ['model'] = 'gbtaxistarlight',
        ['price'] = 5000,
        ['category'] = 'service',
        ['categoryLabel'] = 'Service',
        ['hash'] = `gbtaxistarlight`,
        ['shop'] = 'pdm',
    },
    ['gbvoyagerg'] = {
        ['name'] = 'Voyager Trash Truck',
        ['brand'] = 'MTL',
        ['model'] = 'gbvoyagerg',
        ['price'] = 5000,
        ['category'] = 'service',
        ['categoryLabel'] = 'Service',
        ['hash'] = `gbvoyagerg`,
        ['shop'] = 'pdm',
    },
    ['gbvoyager'] = {
        ['name'] = 'Voyager 6x4-T',
        ['brand'] = 'MTL',
        ['model'] = 'gbvoyager',
        ['price'] = 5000,
        ['category'] = 'commercial',
        ['categoryLabel'] = 'Commercial',
        ['hash'] = `gbvoyager`,
        ['shop'] = 'pdm',
    },
    ['gbvoyager2'] = {
        ['name'] = 'Voyager 4x2-T',
        ['brand'] = 'MTL',
        ['model'] = 'gbvoyager2',
        ['price'] = 5000,
        ['category'] = 'commercial',
        ['categoryLabel'] = 'Commercial',
        ['hash'] = `gbvoyager2`,
        ['shop'] = 'pdm',
    },
    ['gbvoyagerb'] = {
        ['name'] = 'Voyager 6x4-B',
        ['brand'] = 'MTL',
        ['model'] = 'gbvoyagerb',
        ['price'] = 5000,
        ['category'] = 'commercial',
        ['categoryLabel'] = 'Commercial',
        ['hash'] = `gbvoyagerb`,
        ['shop'] = 'pdm',
    },
    ['gbvoyagerb2'] = {
        ['name'] = 'Voyager 4x2-B',
        ['brand'] = 'MTL',
        ['model'] = 'gbvoyagerb2',
        ['price'] = 5000,
        ['category'] = 'commercial',
        ['categoryLabel'] = 'Commercial',
        ['hash'] = `gbvoyagerb2`,
        ['shop'] = 'pdm',
    },
    ['gbvoyagerh'] = {
        ['name'] = 'Voyager 6x2-H',
        ['brand'] = 'MTL',
        ['model'] = 'gbvoyagerh',
        ['price'] = 5000,
        ['category'] = 'commercial',
        ['categoryLabel'] = 'Commercial',
        ['hash'] = `gbvoyagerh`,
        ['shop'] = 'pdm',
    },
    ['gbemsbisonstx'] = {
        ['name'] = 'Bison STX Ambulance',
        ['brand'] = 'Bravado',
        ['model'] = 'gbemsbisonstx',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbemsbisonstx`,
        ['shop'] = 'pdm',
    },
    ['gbemsesperta'] = {
        ['name'] = 'Esperta Ambulance',
        ['brand'] = 'Bravado',
        ['model'] = 'gbemsesperta',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbemsesperta`,
        ['shop'] = 'pdm',
    },
    ['gbfirevoyager'] = {
        ['name'] = 'Voyager Fire Truck',
        ['brand'] = 'MTL',
        ['model'] = 'gbfirevoyager',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbfirevoyager`,
        ['shop'] = 'pdm',
    },
    ['gbpolbisonhf'] = {
        ['name'] = 'Bison HF Police',
        ['brand'] = 'Bravado',
        ['model'] = 'gbpolbisonhf',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolbisonhf`,
        ['shop'] = 'pdm',
    },
    ['gbpolbisonstx'] = {
        ['name'] = 'Bison STX Police',
        ['brand'] = 'Bravado',
        ['model'] = 'gbpolbisonstx',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolbisonstx`,
        ['shop'] = 'pdm',
    },
    ['gbpolcometcl'] = {
        ['name'] = 'Comet Classic Police',
        ['brand'] = 'Pfister',
        ['model'] = 'gbpolcometcl',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolcometcl`,
        ['shop'] = 'pdm',
    },
    ['gbpolcomets2r'] = {
        ['name'] = 'Comet S2R Police',
        ['brand'] = 'Pfister',
        ['model'] = 'gbpolcomets2r',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolcomets2r`,
        ['shop'] = 'pdm',
    },
    ['gbpoldomgsx'] = {
        ['name'] = 'Dominator GSX Police',
        ['brand'] = 'Vapid',
        ['model'] = 'gbpoldomgsx',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpoldomgsx`,
        ['shop'] = 'pdm',
    },
    ['gbpolprospero'] = {
        ['name'] = 'Prospero Police',
        ['brand'] = 'Pegassi',
        ['model'] = 'gbpolprospero',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolprospero`,
        ['shop'] = 'pdm',
    },
    ['gbpolsolace'] = {
        ['name'] = 'Solace Police',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'gbpolsolace',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolsolace`,
        ['shop'] = 'pdm',
    },
    ['gbpolstanier'] = {
        ['name'] = 'Stainer LE Police',
        ['brand'] = 'Vapid',
        ['model'] = 'gbpolstanier',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolstanier`,
        ['shop'] = 'pdm',
    },
    ['gbpolstarlight'] = {
        ['name'] = 'Starlight Police',
        ['brand'] = 'Vulcar',
        ['model'] = 'gbpolstarlight',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolstarlight`,
        ['shop'] = 'pdm',
    },
    ['gbpolsultanrsx'] = {
        ['name'] = 'Sultan RSX Police',
        ['brand'] = 'Karin',
        ['model'] = 'gbpolsultanrsx',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolsultanrsx`,
        ['shop'] = 'pdm',
    },
    ['gbpoltahomagt'] = {
        ['name'] = 'Tahoma GT Police',
        ['brand'] = 'Declasse',
        ['model'] = 'gbpoltahomagt',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpoltahomagt`,
        ['shop'] = 'pdm',
    },
    ['gbpoltr3s'] = {
        ['name'] = 'TR3-S Police',
        ['brand'] = 'Progen',
        ['model'] = 'gbpoltr3s',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpoltr3s`,
        ['shop'] = 'pdm',
    },
    ['gbpolturismogt'] = {
        ['name'] = 'Turismo GT Police',
        ['brand'] = 'Grotti',
        ['model'] = 'gbpolturismogt',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolturismogt`,
        ['shop'] = 'pdm',
    },
    ['gbarcherpro2'] = {
        ['name'] = 'Archer Pro II',
        ['brand'] = 'Maibatsu',
        ['model'] = 'gbarcherpro2',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbarcherpro2`,
        ['shop'] = 'pdm',
    },
    ['gbargento2f'] = {
        ['name'] = 'Argento 2F',
        ['brand'] = 'Obey',
        ['model'] = 'gbargento2f',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbargento2f`,
        ['shop'] = 'pdm',
    },
    ['gbargento7fs'] = {
        ['name'] = 'Argento 7F Sportsback',
        ['brand'] = 'Obey',
        ['model'] = 'gbargento7fs',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbargento7fs`,
        ['shop'] = 'pdm',
    },
    ['gbcheetahs'] = {
        ['name'] = 'Grotti Cheetah S',
        ['brand'] = 'Grotti',
        ['model'] = 'gbcheetahs',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbcheetahs`,
        ['shop'] = 'pdm',
    },
    ['gbcometclf'] = {
        ['name'] = 'Comet Classic Florio',
        ['brand'] = 'Pfister',
        ['model'] = 'gbcometclf',
        ['price'] = 5000,
        ['category'] = 'sportsclassic',
        ['categoryLabel'] = 'Sports Classic',
        ['hash'] = `gbcometclf`,
        ['shop'] = 'pdm',
    },
    ['gbcomets1tf'] = {
        ['name'] = 'Comet S1 Turbo Florio',
        ['brand'] = 'Pfister',
        ['model'] = 'gbcomets1tf',
        ['price'] = 5000,
        ['category'] = 'sportsclassic',
        ['categoryLabel'] = 'Sports Classic',
        ['hash'] = `gbcomets1tf`,
        ['shop'] = 'pdm',
    },
    ['gbcyphergts'] = {
        ['name'] = 'Cypher GTS',
        ['brand'] = 'Ubermacht',
        ['model'] = 'gbcyphergts',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbcyphergts`,
        ['shop'] = 'pdm',
    },
    ['gbdelivere'] = {
        ['name'] = 'Deliver-E',
        ['brand'] = 'Hijak',
        ['model'] = 'gbdelivere',
        ['price'] = 5000,
        ['category'] = 'commercial',
        ['categoryLabel'] = 'Commercial',
        ['hash'] = `gbdelivere`,
        ['shop'] = 'pdm',
    },
    ['gbechelon'] = {
        ['name'] = 'Echelon',
        ['brand'] = 'BF',
        ['model'] = 'gbechelon',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbechelon`,
        ['shop'] = 'pdm',
    },
    ['gbechelons'] = {
        ['name'] = 'Echelon Sportsback',
        ['brand'] = 'BF',
        ['model'] = 'gbechelons',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbechelons`,
        ['shop'] = 'pdm',
    },
    ['gbelegyrh2'] = {
        ['name'] = 'Elegy RH2',
        ['brand'] = 'Annis',
        ['model'] = 'gbelegyrh2',
        ['price'] = 5000,
        ['category'] = 'sportsclassic',
        ['categoryLabel'] = 'Sports Classic',
        ['hash'] = `gbelegyrh2`,
        ['shop'] = 'pdm',
    },
    ['gbemssteed'] = {
        ['name'] = 'Steed Ambulance',
        ['brand'] = 'Vapid',
        ['model'] = 'gbemssteed',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbemssteed`,
        ['shop'] = 'pdm',
    },
    ['gberotiq'] = {
        ['name'] = 'E-Rotiq',
        ['brand'] = 'Bollokan',
        ['model'] = 'gberotiq',
        ['price'] = 5000,
        ['category'] = 'suv',
        ['categoryLabel'] = 'SUV',
        ['hash'] = `gberotiq`,
        ['shop'] = 'pdm',
    },
    ['gbesurfer'] = {
        ['name'] = 'e-Surfer',
        ['brand'] = 'BF',
        ['model'] = 'gbesurfer',
        ['price'] = 5000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `gbesurfer`,
        ['shop'] = 'pdm',
    },
    ['gbhedra'] = {
        ['name'] = 'Hedra',
        ['brand'] = 'Vulcar',
        ['model'] = 'gbhedra',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbhedra`,
        ['shop'] = 'pdm',
    },
    ['gbhedrakombi'] = {
        ['name'] = 'Hedra Kombi',
        ['brand'] = 'Vulcar',
        ['model'] = 'gbhedrakombi',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbhedrakombi`,
        ['shop'] = 'pdm',
    },
    ['gbhurricane'] = {
        ['name'] = 'Hurricane',
        ['brand'] = 'Brute',
        ['model'] = 'gbhurricane',
        ['price'] = 5000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `gbhurricane`,
        ['shop'] = 'pdm',
    },
    ['gbimpalerdlx'] = {
        ['name'] = 'Impaler Deluxe',
        ['brand'] = 'Declasse',
        ['model'] = 'gbimpalerdlx',
        ['price'] = 5000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `gbimpalerdlx`,
        ['shop'] = 'pdm',
    },
    ['gbmochi'] = {
        ['name'] = 'Mochi',
        ['brand'] = 'Annis',
        ['model'] = 'gbmochi',
        ['price'] = 5000,
        ['category'] = 'compacts',
        ['categoryLabel'] = 'Compacts',
        ['hash'] = `gbmochi`,
        ['shop'] = 'pdm',
    },
    ['gbmugello'] = {
        ['name'] = 'Mugello',
        ['brand'] = 'Grotti',
        ['model'] = 'gbmugello',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbmugello`,
        ['shop'] = 'pdm',
    },
    ['gbpoladmiral'] = {
        ['name'] = 'Admiral Police',
        ['brand'] = 'Vapid',
        ['model'] = 'gbpoladmiral',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpoladmiral`,
        ['shop'] = 'pdm',
    },
    ['gbpolargento7f'] = {
        ['name'] = 'Argento 7F Police',
        ['brand'] = 'Obey',
        ['model'] = 'gbpolargento7f',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolargento7f`,
        ['shop'] = 'pdm',
    },
    ['gbpolbanshees'] = {
        ['name'] = 'Banshee S Police',
        ['brand'] = 'Bravado',
        ['model'] = 'gbpolbanshees',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolbanshees`,
        ['shop'] = 'pdm',
    },
    ['gbpolclubxr'] = {
        ['name'] = 'Club XR Police',
        ['brand'] = 'BF',
        ['model'] = 'gbpolclubxr',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolclubxr`,
        ['shop'] = 'pdm',
    },
    ['gbpolechelon'] = {
        ['name'] = 'Echelon Police',
        ['brand'] = 'BF',
        ['model'] = 'gbpolechelon',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolechelon`,
        ['shop'] = 'pdm',
    },
    ['gbpoleon'] = {
        ['name'] = 'Eon Police',
        ['brand'] = 'Coil',
        ['model'] = 'gbpoleon',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpoleon`,
        ['shop'] = 'pdm',
    },
    ['gbpolesperta'] = {
        ['name'] = 'Esperta Police',
        ['brand'] = 'Bravado',
        ['model'] = 'gbpolesperta',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolesperta`,
        ['shop'] = 'pdm',
    },
    ['gbpolgresley'] = {
        ['name'] = 'Gresley Police',
        ['brand'] = 'Bravado',
        ['model'] = 'gbpolgresley',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolgresley`,
        ['shop'] = 'pdm',
    },
    ['gbpolhedra'] = {
        ['name'] = 'Hedra Police',
        ['brand'] = 'Vulcar',
        ['model'] = 'gbpolhedra',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolhedra`,
        ['shop'] = 'pdm',
    },
    ['gbpolimpaler'] = {
        ['name'] = 'Impaler Police',
        ['brand'] = 'Declasse',
        ['model'] = 'gbpolimpaler',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolimpaler`,
        ['shop'] = 'pdm',
    },
    ['gbpolmojave'] = {
        ['name'] = 'Mojave Police',
        ['brand'] = 'Karin',
        ['model'] = 'gbpolmojave',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolmojave`,
        ['shop'] = 'pdm',
    },
    ['gbpolscoutgsx'] = {
        ['name'] = 'Scout GSX Police',
        ['brand'] = 'Vapid',
        ['model'] = 'gbpolscoutgsx',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolscoutgsx`,
        ['shop'] = 'pdm',
    },
    ['gbpolsentinelgts'] = {
        ['name'] = 'Sentinel GTS Police',
        ['brand'] = 'Ubermacht',
        ['model'] = 'gbpolsentinelgts',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolsentinelgts`,
        ['shop'] = 'pdm',
    },
    ['gbpolstanier'] = {
        ['name'] = 'Stainer LE Police',
        ['brand'] = 'Vapid',
        ['model'] = 'gbpolstanier',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolstanier`,
        ['shop'] = 'pdm',
    },
    ['gbpolsteedvan'] = {
        ['name'] = 'Steed Police',
        ['brand'] = 'Vapid',
        ['model'] = 'gbpolsteedvan',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolsteedvan`,
        ['shop'] = 'pdm',
    },
    ['gbpolterrorizer'] = {
        ['name'] = 'Terrorizer Police',
        ['brand'] = 'HVY',
        ['model'] = 'gbpolterrorizer',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolterrorizer`,
        ['shop'] = 'pdm',
    },
    ['gbretinueloz'] = {
        ['name'] = 'Retinue Lozspeed',
        ['brand'] = 'Vapid',
        ['model'] = 'gbretinueloz',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbretinueloz`,
        ['shop'] = 'pdm',
    },
    ['gbromulus'] = {
        ['name'] = 'Romulus',
        ['brand'] = 'Annis',
        ['model'] = 'gbromulus',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbromulus`,
        ['shop'] = 'pdm',
    },
    ['gbrumina'] = {
        ['name'] = 'Rumina',
        ['brand'] = 'Annis',
        ['model'] = 'gbrumina',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbrumina`,
        ['shop'] = 'pdm',
    },
    ['gbscoutgsx'] = {
        ['name'] = 'Scout GSX',
        ['brand'] = 'Vapid',
        ['model'] = 'gbscoutgsx',
        ['price'] = 5000,
        ['category'] = 'suv',
        ['categoryLabel'] = 'SUV',
        ['hash'] = `gbscoutgsx`,
        ['shop'] = 'pdm',
    },
    ['gbsteedcrew'] = {
        ['name'] = 'Steed Crewmate',
        ['brand'] = 'Vapid',
        ['model'] = 'gbsteedcrew',
        ['price'] = 5000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `gbsteedcrew`,
        ['shop'] = 'pdm',
    },
    ['gbsteedvan'] = {
        ['name'] = 'Steed',
        ['brand'] = 'Vapid',
        ['model'] = 'gbsteedvan',
        ['price'] = 5000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `gbsteedvan`,
        ['shop'] = 'pdm',
    },
    ['gbtempestafs'] = {
        ['name'] = 'Tempesta Fuoristrada',
        ['brand'] = 'Pegassi',
        ['model'] = 'gbtempestafs',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbtempestafs`,
        ['shop'] = 'pdm',
    },
    ['gbvigerorat'] = {
        ['name'] = 'Vigero Rattler',
        ['brand'] = 'Declasse',
        ['model'] = 'gbvigerorat',
        ['price'] = 5000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `gbvigerorat`,
        ['shop'] = 'pdm',
    },
    ['gbzeitgeist'] = {
        ['name'] = 'Zeitgeist',
        ['brand'] = 'Benefactor-Progen',
        ['model'] = 'gbzeitgeist',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbzeitgeist`,
        ['shop'] = 'pdm',
    },
    ['gbzr350'] = {
        ['name'] = 'ZR350',
        ['brand'] = 'Annis',
        ['model'] = 'gbzr350',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbzr350`,
        ['shop'] = 'pdm',
    },
    ['gbbuffalohf'] = {
        ['name'] = 'Buffalo HF',
        ['brand'] = 'Bravado',
        ['model'] = 'gbbuffalohf',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbbuffalohf`,
        ['shop'] = 'pdm',
    },
    ['gbnexus1'] = {
        ['name'] = 'Nexus',
        ['brand'] = 'Dinka',
        ['model'] = 'gbnexus1',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbnexus1`,
        ['shop'] = 'pdm',
    },
    ['gbtokage'] = {
        ['name'] = 'Tokage JDM',
        ['brand'] = 'Dinka',
        ['model'] = 'gbtokage',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbtokage`,
        ['shop'] = 'pdm',
    },
    ['gbtokage2'] = {
        ['name'] = 'Tokage USDM',
        ['brand'] = 'Dinka',
        ['model'] = 'gbtokage2',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbtokage2`,
        ['shop'] = 'pdm',
    },
    ['gbnobile'] = {
        ['name'] = 'Nobile',
        ['brand'] = 'Grotti',
        ['model'] = 'gbnobile',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbnobile`,
        ['shop'] = 'pdm',
    },
    ['gbzero'] = {
        ['name'] = 'Zero',
        ['brand'] = 'Grotti',
        ['model'] = 'gbzero',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbzero`,
        ['shop'] = 'pdm',
    },
    ['gbdice'] = {
        ['name'] = 'Dice',
        ['brand'] = 'Karin',
        ['model'] = 'gbdice',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbdice`,
        ['shop'] = 'pdm',
    },
    ['gbkisairs'] = {
        ['name'] = 'Kisai RS',
        ['brand'] = 'Karin',
        ['model'] = 'gbkisairs',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbkisairs`,
        ['shop'] = 'pdm',
    },
    ['gbshogun'] = {
        ['name'] = 'Shogun',
        ['brand'] = 'Karin',
        ['model'] = 'gbshogun',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbshogun`,
        ['shop'] = 'pdm',
    },
    ['gblaner4fh'] = {
        ['name'] = 'Laner 4FH',
        ['brand'] = 'Obey',
        ['model'] = 'gblaner4fh',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gblaner4fh`,
        ['shop'] = 'pdm',
    },
    ['gbtoreroxpr1'] = {
        ['name'] = 'Torero XPR-1',
        ['brand'] = 'Pegassi',
        ['model'] = 'gbtoreroxpr1',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbtoreroxpr1`,
        ['shop'] = 'pdm',
    },
    ['gbmeteor'] = {
        ['name'] = 'Meteor',
        ['brand'] = 'Pfister',
        ['model'] = 'gbmeteor',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbmeteor`,
        ['shop'] = 'pdm',
    },
    ['gbemerus'] = {
        ['name'] = 'Emerus',
        ['brand'] = 'Progen',
        ['model'] = 'gbemerus',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbemerus`,
        ['shop'] = 'pdm',
    },
    ['gbcaracaragsx'] = {
        ['name'] = 'Caracara GSX',
        ['brand'] = 'Vapid',
        ['model'] = 'gbcaracaragsx',
        ['price'] = 5000,
        ['category'] = 'offroad',
        ['categoryLabel'] = 'Offroad',
        ['hash'] = `gbcaracaragsx`,
        ['shop'] = 'pdm',
    },
    ['gbdomle'] = {
        ['name'] = 'Dominator LE',
        ['brand'] = 'Vapid',
        ['model'] = 'gbdomle',
        ['price'] = 5000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `gbdomle`,
        ['shop'] = 'pdm',
    },
}
